import { Inter } from 'next/font/google'
import './globals.css'
import Layout from '@components/Layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const RootLayout = () => (
  <html lang="en">
    <body className={inter.className}>
      <Layout />
    </body>
  </html>
)

export default RootLayout
